export const MOCK_CLIENTI_FORNITORI = [
  {
    cod: 1101,
    nominativo: "Clinica Sant'Anna",
    tipo: "cliente",
    tipoRaw: "CLIENTE",
    piva: "01784530988",
    codFiscale: "01784530988",
    indirizzo: "Via Roma 11",
    citta: "Milano",
    cap: "20121",
    provincia: "MI",
    regione: "Lombardia",
    telefoni: "+39 02 4455667",
    email: "acquisti@clinicasantanna.it",
    pec: "clinicasantanna@pec.it",
    note: "Reparto radiologia",
    agenziaRiferimento: "Nord Ovest"
  },
  {
    cod: 1102,
    nominativo: "Poliambulatorio Delta",
    tipo: "cliente",
    tipoRaw: "CLIENTE",
    piva: "03345670966",
    codFiscale: "03345670966",
    indirizzo: "Via Verdi 8",
    citta: "Bergamo",
    cap: "24121",
    provincia: "BG",
    regione: "Lombardia",
    telefoni: "+39 035 900112",
    email: "info@poliodelta.it",
    pec: "poliodelta@pec.it",
    note: "",
    agenziaRiferimento: "Nord Est"
  },
  {
    cod: 2201,
    nominativo: "Medical Parts Srl",
    tipo: "fornitore",
    tipoRaw: "FORNITORE",
    piva: "02890070123",
    codFiscale: "02890070123",
    indirizzo: "Via Galvani 2",
    citta: "Padova",
    cap: "35100",
    provincia: "PD",
    regione: "Veneto",
    telefoni: "+39 049 776655",
    email: "sales@medicalparts.it",
    pec: "medicalparts@pec.it",
    note: "Consegna 48h",
    agenziaRiferimento: ""
  },
  {
    cod: 2202,
    nominativo: "Forniture Biomediche Spa",
    tipo: "fornitore",
    tipoRaw: "FORNITORE",
    piva: "01234560456",
    codFiscale: "01234560456",
    indirizzo: "Viale Europa 44",
    citta: "Bologna",
    cap: "40100",
    provincia: "BO",
    regione: "Emilia-Romagna",
    telefoni: "+39 051 334455",
    email: "commerciale@forniturebiomediche.it",
    pec: "forniturebiomediche@pec.it",
    note: "",
    agenziaRiferimento: ""
  },
  {
    cod: 3301,
    nominativo: "Sanitas Hub",
    tipo: "cliente-fornitore",
    tipoRaw: "CLIENTE/FORNITORE",
    piva: "04561230987",
    codFiscale: "04561230987",
    indirizzo: "Corso Italia 90",
    citta: "Torino",
    cap: "10121",
    provincia: "TO",
    regione: "Piemonte",
    telefoni: "+39 011 998877",
    email: "operations@sanitashub.it",
    pec: "sanitashub@pec.it",
    note: "Partner misto",
    agenziaRiferimento: "Nord Ovest"
  }
];
