import mongoose from "mongoose";

const schema = new mongoose.Schema(
{
  COD: { type: Number, required: true },
  Nominativo: { type: String, required: true },
  Indirizzo: { type: String, required: true },
  Citta: { type: String, required: true, maxlength: 50 },
  CAP: { type: String, required: true, maxlength: 5 },
  telefoni: { type: String, required: false, maxlength: 100 },
  REA: { type: String, required: false },
  PIVA: { type: String, required: true, maxlength: 11 },
  "Camera Commercio": { type: String, required: false, maxlength: 50 },
  "Cod Fiscale": { type: String, required: false, maxlength: 16 },
  Indirizzo1: { type: String, required: false },
  Citta1: { type: String, required: false, maxlength: 50 },
  CAP1: { type: String, required: false, maxlength: 5 },
  telefoni1: { type: String, required: false, maxlength: 100 },
  Banca: { type: String, required: false, maxlength: 50 },
  IBAN: { type: String, required: false, maxlength: 27 },
  Banca1: { type: String, required: false, maxlength: 50 },
  IBAN1: { type: String, required: false, maxlength: 27 },
  email1: { type: String, required: false, maxlength: 50 },
  email2: { type: String, required: false, maxlength: 50 },
  email3: { type: String, required: false, maxlength: 50 },
  note: { type: String, required: false },
  Logo: { type: Buffer, required: false },
  "Firma Validatore": { type: Buffer, required: false },
  ordine: { type: Number, required: false },
  "Nome Amministratore": { type: String, required: false, maxlength: 150 },
  LastEditDate: { type: Date, required: false },
  CreationDate: { type: Date, required: false },
  "Indirizzo InvioFatture": { type: String, required: false },
  "Indirizzo InvioNotaSpese": { type: String, required: false },
  "Codice Identificativo": { type: String, required: false, maxlength: 50 },
  PR: { type: String, required: false, maxlength: 2 },
  Stato: { type: String, required: false, maxlength: 2 },
  "Capitale Sociale": { type: Number, required: false },
  Socio: { type: String, required: false, maxlength: 5 },
  "Stato Liquidazione": { type: String, required: false, maxlength: 5 },
  "N.Civico": { type: String, required: false, maxlength: 10 },
  ATECO: { type: String, required: false, maxlength: 50 },
  Attiva: { type: Boolean, required: false },
  LogoDX_UP: { type: Buffer, required: false },
  LogoSX_DW: { type: Buffer, required: false },
  Titolo1DX_UP: { type: String, required: false, maxlength: 50 },
  Titolo2DX_UP: { type: String, required: false, maxlength: 50 },
  Titolo1SX_UP: { type: String, required: false, maxlength: 50 },
  Titolo2SX_UP: { type: String, required: false, maxlength: 50 },
  PiePagina1: { type: String, required: false },
  PiePagina2: { type: String, required: false },
  LogoDX_DW: { type: Buffer, required: false },
  Web: { type: String, required: false, maxlength: 100 },
  LogoSmall: { type: Buffer, required: false },
  Timbro: { type: Buffer, required: false },
  "Provincia CCIAA": { type: String, required: false, maxlength: 50 },
  pass_email1: { type: String, required: false, maxlength: 50 },
  pass_email2: { type: String, required: false, maxlength: 50 },
  pass_email3: { type: String, required: false, maxlength: 50 }
},
{ collection: "Anagrafica", timestamps: false }
);

schema.index({ COD: 1 }, { unique: true });

export default mongoose.model("Anagrafica", schema);
