import mongoose from "mongoose";

const schema = new mongoose.Schema(
{
  user: { type: String, required: true, maxlength: 15 },
  password: { type: String, required: true, maxlength: 15 },
  nome: { type: String, required: true, maxlength: 50 },
  cognome: { type: String, required: true, maxlength: 50 },
  "data di nascita": { type: Date, required: false },
  codfiscale: { type: String, required: false, maxlength: 16 },
  ruolo: { type: String, required: false, maxlength: 50 },
  "Titolo di Studio": { type: String, required: false },
  Curriculum: { type: String, required: false },
  "Referente Interno": { type: String, required: false, maxlength: 100 },
  "Telefono Fisso": { type: String, required: false, maxlength: 50 },
  "Cellulare Aziendale": { type: String, required: false, maxlength: 50 },
  "Cellulare personale": { type: String, required: false, maxlength: 50 },
  matricola: { type: String, required: false, maxlength: 50 },
  "assunto dal": { type: Date, required: false },
  email1: { type: String, required: false, maxlength: 50 },
  email2: { type: String, required: false, maxlength: 50 },
  email3: { type: String, required: false, maxlength: 50 },
  "Data Consegna Auto": { type: Date, required: false },
  "Modello Auto": { type: String, required: false, maxlength: 50 },
  "targa auto": { type: String, required: false },
  "Scadenza Auto": { type: Date, required: false },
  "Rif Contratto Auto": { type: String, required: false },
  "Km da contratto": { type: Number, required: false },
  "Km Attuali": { type: Number, required: false },
  note: { type: String, required: false },
  data_rec: { type: Buffer, required: true },
  autorizza: { type: String, required: true, maxlength: 48 },
  foto: { type: Buffer, required: false },
  "Ultimo Login": { type: Date, required: false },
  "Luogo di Nascita": { type: String, required: false },
  "Indirizzo Residenza": { type: String, required: false },
  "Numero Carta Identità": { type: String, required: false, maxlength: 50 },
  "Numero Patente": { type: String, required: false, maxlength: 50 },
  "Numero Passaporto": { type: String, required: false, maxlength: 50 },
  attivo: { type: Boolean, required: true },
  "Data Consegna PC": { type: Date, required: false },
  "Modello PC": { type: String, required: false },
  "Seriale PC": { type: String, required: false, maxlength: 50 },
  Num_CartaCredito: { type: String, required: false, maxlength: 50 },
  "Scadenza Carta": { type: Date, required: false },
  "Tools Attribuiti": { type: String, required: false },
  "Altri Benefit": { type: String, required: false },
  Firma: { type: Buffer, required: false },
  cod: { type: Number, required: true },
  LastEditDate: { type: Date, required: false },
  CreationDate: { type: Date, required: false },
  "Validatore Offerte": { type: Boolean, required: false },
  "Validatore Contratti": { type: Boolean, required: false },
  "Validatore Ordini": { type: Boolean, required: false },
  "Versione in uso": { type: String, required: false, maxlength: 50 },
  "Centro di Costo": { type: String, required: false, maxlength: 100 },
  "Service Engineer": { type: Boolean, required: false },
  ValidatoreNS: { type: Boolean, required: false },
  ValidatoreComunicazioni: { type: Boolean, required: false },
  "Versione Precedente": { type: String, required: false, maxlength: 50 },
  "Numero Interno": { type: String, required: false, maxlength: 10 },
  "Numero Esterno": { type: String, required: false, maxlength: 40 },
  "Firma Mail": { type: String, required: false },
  online: { type: Boolean, required: false },
  Commerciale: { type: Boolean, required: false },
  "Validatore CheckInterne": { type: Boolean, required: false },
  cod_azienda: { type: Number, required: false },
  "Validatore Commessa": { type: Boolean, required: false },
  "Validatore CommessaPO": { type: Boolean, required: false },
  "Validatore CommessaAT": { type: Boolean, required: false },
  "Validatore CommessaUA": { type: Boolean, required: false },
  Manager: { type: Boolean, required: false },
  Timbro: { type: Buffer, required: false },
  "Validatore Certificazioni": { type: Boolean, required: false },
  Local_IP: { type: String, required: false, maxlength: 50 },
  "Nome Completo": { type: String, required: false, maxlength: 101 },
  "Validatore Presenze": { type: Boolean, required: false },
  WebCam: { type: Boolean, required: false },
  Lan: { type: Boolean, required: false },
  "Durata Contratto Auto": { type: Number, required: false },
  MediaKmMese: { type: Number, required: false },
  ProiezioneKM: { type: Number, required: false }
},
{ collection: "Utenti", timestamps: false }
);

schema.index({ cod: 1 }, { unique: true });

export default mongoose.model("Utenti", schema);
